config/routes.rb
Rails.application.routes.draw do
  
 
  root             'static_pages#index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home'    => 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
  	render text: "Eello World"   
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  #index main page
  def index
  end
  
  # Home Page Methord with no body
  def home
  end

  # Help Page methord with no body
  def help
  end

  # About Page methord with no body
  def about
  end

  def contact
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      "#{page_title} | #{base_title}"                 # String interpolation
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="container">
 
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
     <!-- <li><a href="http://news.railstutorial.org/">News</a></li>  -->
     <li><%= link_to "News", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header >
  <div class="container">
   
   <!-- Navigation Panel -->
    <nav>
      <ul class="button">
        <li><%= link_to "Home",   root_path %></li>
         <li><%= link_to "Blog", "#" %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", home_path %></li>
      </ul>
    </nav>


  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>



<!-- Head and title of the application --> 
  <head>
    <title >
    <%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>




 <body class="container">


  <!-- eader of the application  => included the patials header -->
  <div class="row">

     <div class="columns ten"> </div>
      <div class="columns five"> <%= render 'layouts/header' %> </div>

  </div>


    <!-- Main Body goes here i.e. the other pages layout goes here--> 
    <div class="row">
    <div class="columns nine">   <%= yield %>  </div>
    </div>

      
      <!-- footer of the application goes here -->
      <div class="row">
      <div class="columns ten">  </div>
      <div class="columns five"> <%= render 'layouts/footer' %> </div>
      </div>
    
</body>



</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p >
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<%provide(:title , "Contact") %>
<h1>Contact</h1>
<p>
  Contact me : 
  <a href="https://plus.google.com/u/0/+KushKD/posts">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Start Learning Rails from here</a>.
 
  
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div >


  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>

 <body class="container">


  <!-- eader of the application  => included the patials header -->
  <div class="row">

    
    <div class="columns five" id="bloginfo"> </div>
   </div>

      
     <!--  Kush kumar dhawan-->
    
</body>



</html>